var books = [
  "ULYSSES by James Joyce",
  "THE GREAT GATSBY by F. Scott Fitzgerald",
  "A PORTRAIT OF THE ARTIST AS A YOUNG MAN by James Joyce",
  "LOLITA by Vladimir Nabokov",
  "Pride and Prejudice by Jane Austen",
  "To Kill A Mockingbird by Harper Lee",
  "In Search of Lost Time by Marcel Proust",
  "Don Quixote by Miguel de Cervantes",
  "Moby Dick by Herman Melville",
  "Hamlet by William Shakespeare",
  "War and Peace by Leo Tolstoy",
  "The Odyssey by Homer",
  "The Divine Comedy by Dante Alighieri",
  "Madame Bovary by Gustave Flaubert",
  "The Brothers Karamazov by Fyodor Dostoyevsky",
  "One Hundred Years of Solitude by Gabriel Garcia Marquez",
  "The Iliad by Homer",
  "Dracula by Bram Stoker",
  "Anna Karenina by Leo Tolstoy",
  "Crime and Punishment by Fyodor Dostoyevsky",
  "The Sound and the Fury by William Faulkner",
  "Bleak House by Charles Dickens",
  "David Copperfield by Charles Dickens",
  "Wuthering Heights by Emile Bronte",
  "The Catcher in the Rye by J. D. Salinger",
  "Nineteen Eighty Four by George Orwell",
  "Brave New World by Aldox Huxley",
  "Heart of Darkness by Joseph Conrad",
  "To the Lighthouse by Virginia Woolf",
  "Absalom, Absalom! by William Faulkner",
  "Middlemarch by George Eliot",
  "The Martian by Andy Weir",
  "The Trial by Franz Kafka",
  "Metamorphosis by Franz Kafka",
  "The Red and the Black by Stendhal",
  "The Grapes of Wrath by John Steinbeck",
  "The Aeneid by Virgil",
  "Mrs. Dalloway by Virginia Woolf",
  "Leaves of Grass by Walt Whitman",
  "Candide by Voltaire",
  "Jane Eyre by Charlotte Bronte",
  "As I Lay Dying by William Faulkner",
  "The Sun Also Rises by Ernest Hemingway",
  "The Grapes of Wrath by John Steinbeck",
  "The Lord of the Rings by J. R. R. Tolkien",
  "The Portrait of a Lady by Henry James",
  "Golden Bowl by Henry James",
  "Oedipus the King by Sophocles",
  "Mediations by Marcus Aurelius",
  "Les Misérables by Victor Hugo",
  "Pale Fire by Vladimir Nabokov",
  "The Idiot by Fyodor Dostoyevsky",
  "Antigone by Sophocles",
  "Macbeth by William Shakespeare",
  "The Magic Mountain by Thomas Mann",
  "Emma by Jane Austen",
  "For Whom the Bell Tolls by Ernest Hemingway",
  "Frankenstein by Mary Shelley",
  "Journey to the End of The Night by Louis-Ferdinand Céline",
  "Oresteia by Aeschylus",
  "The Old Man and the Sea by Ernest Hemingway",
  "Vanity Fair by William Makepeace Thackeray",
  "Under the Volcano by Malcolm Lowry",
  "Gargantua and Pantagruel by Francois Rabelais",
  "Things Fall Apart by Chinua Achebe",
  " The Flowers of Evil by Charles Baudelaire",
  "The Tin Drum by Günter Grass",
  "The Good Soldier by Ford Madox Ford",
  "A Farewell to Arms by Ernest Hemingway",
  "Poems of Emily Dickinson by Emily Dickinson",
  "Into the Wild by John Krakauer",
  "Father Goriot by Honoré de Balzac",
  "The Tale of Genji by Murasaki Shikibu",
  "The Charterhouse of Parma by Stendhal",
  "Fathers and Sons by Ivan Turgenev",
  "Metamorphoses by Ovid",
  "Waiting for Godot by Samuel Beckett",
  "The Waste Land by T. S. Eliot",
  "A Sentimental Education by Gustave Flaubert",
  "Cousin Bette by Honoré de Balzac",
  "Dangerous Liaison by Pierre Choderlos de Laclos",
  "Animal Farm by George Orwell",
  "Tess of the d'Urbervilles by Thomas Hardy",
  "Lord of the Flies by William Golding",
  "King Lear by William Shakespeare",
  "American Pastoral by Philip Roth",
  "The Age of Innocence by Edith Wharton",
  "Treasure Island by Robert Louis Stevenson",
  "All the King's Men by Robert Penn Warren",
  "Blood Meridian by Cormac McCarthy",
  "Native Son by Richard Wright",
  "Buddenbrooks by Thomas Mann",
  "Sons and Lovers by D. H. Lawrence",
  "Rabbit, Run by John Updike",
  "Slaughterhouse-Five by Kurt Vonnegut",
  "Their Eyes Were Watching God by Zora Neale Hurston",
  "A Season in Hell by Arthur Rimbaud",
  "The Count of Monte Cristo by Alexandre Dumas",
  "A Doll's House by Henrik Ibsen",
  "The Ambassadors by Henry James",
  "The Bostonians by Henry James",
  "The Moviegoer by Walker Percy",
  "The Complete Sherlock Holmes by Arthur Conan Doyle",
  "Set in Darkness by Ian Rankin",
  "Electra by Sophocles",
  "Medea by Euripides",
  "Doctor Faustus by Thomas Mann",
  " The Big Sleep by Raymond Chandler",
  "One Flew Over the Cuckoo's Nest by Ken Kesey",
  "Lost Illusions by Honoré de Balzac",
  "Doctor Zhivago by Boris Pasternak",
  "The Wind in the Willows by Kenneth Grahame",
  "Light in August by William Faulkner",
  "The Wind-Up Bird Chronicle by Haruki Murakami",
  "Hunger by Knut Hamsun",
  "If on a Winter's Night a Traveller by Italo Calvino",
  "Why Read Classics? by Italo Calvino",
  "Women in Love by D. H. Lawrence",
  "Prometheus Bound by Aeschylus",
  "Lysistrata by Aristophanes",
  "A Clockwork Orange by Anthony Burgess",
  "The Call of the Wild by Jack London",
  "Orlando: A Biography by Virginia Woolf",
  "The Color Purple by Alice Walker",
  "Steppenwolf by Hermann Hesse",
  "Sidhartha by Hermann Hesse",
  "Gravity's Rainbow by Thomas Pynchon",
  "A Breif History of Time by Stephen Hawkings",
  " A Tale of Two Cities by Charles Dickens",
  "I, Claudius by Robert Graves",
  "The Unbearable Lightness of Being by Milan Kundera",
  "The Pickwick Papers by Charles Dickens",
  "Tartuffe by Molière",
  "Seven Against Thebes by Aeschylus",
  "The Persians by Aeschylus",
  "The Suppliants by Aeschylus",
  "De Rerum Natura by Lucretius",
  "Harry Potter And The Philosopher's Stone by J. K. Rowling",
  "Molloy by Samuel Beckett",
  "The Handmaid's Tale by Margaret Atwood",
  "The Golden Notebook by Doris Lessing",
  "The Heart is a Lonely Hunter by Carson McCullers",
  "Rabbit Is Rich by John Updike",
  "The Bacchae by Euripides",
  "The Adventures of Augie March by Saul Bellow",
  "Women of Trachis by Sophocles",
  "Ajax by Sophocles",
  "Philoctetes by Sophocles",
  "The Princess of Cleves by Madame de La Fayette",
  "The Misanthrope by Molière",
  "Independent People by Halldor Laxness",
  "The Man Without Qualities by Robert Musil",
  "Jude the Obscure by Thomas Hardy",
  "Lady Chatterley's Lover by D. H. Lawrence",
  "Pedro Paramo by Juan Rulfo",
  "Tender Is the Night by F. Scott Fitzgerald",
  "Infinite Jest by David Foster Wallace",
  "The Birds by Aristophanes",
  "Memoirs of Hadrian by Marguerite Yourcenar",
  "Of Mice and Men by John Steinbeck",
  "The Corrections by Jonathan Franzen",
  "Berlin Alexanderplatz by Alfred Döblin",
  "Austerlitz by W. G. Sebald",
  "The Lion, The Witch and the Wardrobe by C.S. Lewis",
  "Clarissa by Samuel Richardson",
  "The Rime of the Ancient Mariner by Samuel Taylor Coleridge",
  "Don Juan by Molière",
  " The Miser by Molière",
  "The Book of Disquiet by Fernando Pessoa",
  " The Duino Elegies by Rainer Maria Rilke",
  "Nausea by Jean-Paul Sartre",
  "The Waves by Virginia Woolf",
  "The Long Goodbye: A Novel by Raymond Chandler",
  "The Counterfeiters by André Gide",
  "The Hitchhiker's Guide to the Galaxy by Douglas Adams",
  "The Clouds by Aristophanes",
  "Dune by Frank Herbert",
  "A Prayer for Owen Meany by John Irving",
  "Atonement by Ian McEwan",
  "The Pale King by David Foster Wallace",
  "The Fountainhead by Ayn Rand",
  "Atlas Shrugged by Ayn Rand",
  "The Confusions of Young Törless by Robert Musil",
  "Cloud Atlas by David Mitchell",
  "2666 by Roberto Bolano",
  "A Wrinkle In Time by Madeleine L'Engle",
  "The House of the Spirits by Isabel Allende",
  "Jakob Von Gunten by Robert Walser",
  "The Hound of the Baskervilles by Sir Arthur Conan Doyle",
  "The Odes by Horace",
  "Trojan Women by Euripides",
  "Dream of the Red Chamber by Cao Xueqin",
  "In Our Time by Ernest Hemingway",
  "Money by Martin Amis",
  "A Tree Grows in Brooklyn by Betty Smith",
  "The Brief Wondrous Life of Oscar Wao by Junot Diaz",
  "Tropic of Cancer by Henry Miller",
  "Oblomov by Ivan Goncharov",
  " The Sleepwalkers by Hermann Broch",
  "White Noise by Don DeLillo",
  "The Waste Land and Other Poems by T. S. Eliot",
  "The Temple of the Golden Pavilion by Yukio Mishima",
  "Middlesex by Jeffrey Eugenides",
  "Wide Sargasso Sea by Jean Rhys",
  "The Things They Carried by Tim O'Brien",
  "The Night Manager by John le Carre",
  "Tinker Taylor Soldier Spy by John le Carre",
  "Hanging Gardens by Ian Rankin",
  " Labyrinths by Jorge Luis Borges",
  "White Teeth by Zadie Smith",
  " Death of Virgil by Hermann Broch",
  "The War of the End of the World by Mario Vargas Llosa",
  "The Mill on the Floss by George Eliot",
  "Carry On, Jeeves by P.G. Wodehouse",
  "Invisible Cities by Italo Calvino",
  "Manon Lescaut by Abbe Prevost",
  "The Way We Live Now by Anthony Trollope",
  "The Bell Jar by Sylvia Plath",
  "Neuromancer by William Gibson",
  "Go Tell it on the Mountain by James Baldwin",
  "The Book Thief by Markus Zusak",
  "Uncle Vanya by Anton Chekhov",
  "The Remains of the Day by Kazuo Ishiguro",
  "The Marriage Of Cadmus And Harmony by Roberto Calasso",
  "Naked Lunch by William Burroughs",
  "Krapp's Last Tape by Samuel Beckett",
  "Utopia by Thomas More",
  "The Blind Assassin by Margaret Atwood",
  "Ferdydurke by Witold Gombrowicz",
  "The Importance of Being Earnest by Oscar Wilde",
  "Arrowsmith by Sinclair Lewis",
  "My Name Is Aram by William Saroyan",
  "Scoop by Evelyn Waugh",
  "Portnoy's Complaint by Philip Roth",
  "A Good Man Is Hard to Find by Flannery O'Connor",
  "Silas Marner by George Eliot",
  "Notes from the Underground by Fyodor Dostoyevsky",
  "Bastard Out of Carolina by Dorothy Allison",
  "Main Street by Sinclair Lewis",
  "Parade's End by Ford Madox Ford",
  "Richard III by William Shakespeare",
  "Endgame by Samuel Beckett",
  "Blindness by Jose Saramago",
  "The Sea, The Sea by Iris Murdoch",
  "A Hero of Our Time by Mikhail Lermontov",
  "The Crying of Lot 49 by Thomas Pynchon",
  "Murder on the Orient Express by Agatha Christie",
  "And Then There Were None by Agatha Christie",
  "The Alienist by Caleb Carr",
  "The Power of Habit by Charles Duhigg",
  " The Sound of the Mountain by Yasunari Kawabata",
  "Some Prefer Nettles by Junichiro Tanizaki",
  "Daphnis and Chloe by Longus",
  " The Secret History by Donna Tartt",
  "A Death in the Family by James Agee",
  "Youth by J. M. Coetzee",
  "We by Yevgeny Zamyatin",
  "Betrayed by Rita Hayworth by Manuel Puig",
  "The Ambassadors by Henry James",
  "Great Expectations by Charles Dickens",
  "Miss Lonelyhearts by Nathanael West",
  "The Murder of Roger Ackroyd by Agatha Christie",
  "The Kreutzer Sonata: And Other Stories by Leo Tolstoy"
]

module.exports = books;
